### ISSUE TITLE
tex mode " symbol problem

### ISSUE THREAD

**Issue by shan199105** [oahziur/dotemacs#2]
Sometimes, when typing ", it does not appear as ".

here is the screenshot:
![a2_sub tex emacs today at 2 57 29 pm](https://cloud.githubusercontent.com/assets/2152195/6218518/bc7838aa-b5ec-11e4-98f8-6d95b29d16ac.png)

**Comment by oahziur** [comment]
http://stackoverflow.com/questions/24835536/insert-regular-double-quotes-in-latex-mode-with-auctex
